### ISSUE TITLE
Tesselator breaks rendering with falsetweaks, and multithreading enabled

### ISSUE THREAD

**Issue by unix-supremacist** [GTNewHorizons/GTNHLib#93]
### Your GTNH Discord Username

unixsupremacist

### Mod Version

0.5.20

### Bug Report

![{13D052D4-C278-413D-B1A0-3794AAE8E02A}](https://github.com/user-attachments/assets/90946820-fb29-479c-8eed-5f68ae2aa771)

[StackTrace](https://pastebin.com/u95mh9er)

### Java Version

Java 21

### Mod List or GTNH Pack Version

![{F02CA3B9-9788-407F-9991-A853B335DE03}](https://github.com/user-attachments/assets/2d4912de-2609-4bfa-9b7e-be09bc73019b)

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.

**Comment by FalsePattern** [comment]
Fixed in https://github.com/FalsePattern/FalseTweaks/commit/841098b3d5a96ff7d8d4d57cd45676a985c7c940

**Comment by Caedis** [comment]
Thanks @FalsePattern
